"""make conversation name optional

Revision ID: 029c76a9d3cf
Revises: b2c3d4e5f6a7
Create Date: 2025-12-06 22:17:40.561192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "029c76a9d3cf"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("conversations", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("media_message_id_fkey", "media", type_="foreignkey")
    op.create_foreign_key(None, "media", "messages", ["message_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "media", type_="foreignkey")
    op.create_foreign_key(
        "media_message_id_fkey", "media", "messages", ["message_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column("conversations", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
