"""make idx for user_conversation

Revision ID: 33cbd4d8b6de
Revises: 029c76a9d3cf
Create Date: 2025-12-07 23:19:46.578129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cbd4d8b6de'
down_revision: Union[str, None] = '029c76a9d3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_user_conversation_conv_last_read',
        'user_conversation',
        ['conversation_id', 'last_read_message_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_conversation_conv_last_read', table_name='user_conversation')
    # ### end Alembic commands ###
